// Auto-generated by sync-registry.ts
// Inlines @inkui-cli/core theme and tokens

export const spacing = {
  none: 0,
  xs: 1,
  sm: 1,
  md: 2,
  lg: 3,
  xl: 4,
} as const

export const borderStyles = {
  single: {
    topLeft: '┌',
    top: '─',
    topRight: '┐',
    left: '│',
    right: '│',
    bottomLeft: '└',
    bottom: '─',
    bottomRight: '┘',
    topT: '┬',
    bottomT: '┴',
    leftT: '├',
    rightT: '┤',
    cross: '┼',
  },
  double: {
    topLeft: '╔',
    top: '═',
    topRight: '╗',
    left: '║',
    right: '║',
    bottomLeft: '╚',
    bottom: '═',
    bottomRight: '╝',
    topT: '╦',
    bottomT: '╩',
    leftT: '╠',
    rightT: '╣',
    cross: '╬',
  },
  rounded: {
    topLeft: '╭',
    top: '─',
    topRight: '╮',
    left: '│',
    right: '│',
    bottomLeft: '╰',
    bottom: '─',
    bottomRight: '╯',
    topT: '┬',
    bottomT: '┴',
    leftT: '├',
    rightT: '┤',
    cross: '┼',
  },
  bold: {
    topLeft: '┏',
    top: '━',
    topRight: '┓',
    left: '┃',
    right: '┃',
    bottomLeft: '┗',
    bottom: '━',
    bottomRight: '┛',
    topT: '┳',
    bottomT: '┻',
    leftT: '┣',
    rightT: '┫',
    cross: '╋',
  },
  ascii: {
    topLeft: '+',
    top: '-',
    topRight: '+',
    left: '|',
    right: '|',
    bottomLeft: '+',
    bottom: '-',
    bottomRight: '+',
    topT: '+',
    bottomT: '+',
    leftT: '+',
    rightT: '+',
    cross: '+',
  },
} as const

export type BorderStyle = keyof typeof borderStyles

export const spinnerFrames = {
  dots: ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'],
  line: ['−', '\\', '|', '/'],
  arc: ['◜', '◠', '◝', '◞', '◡', '◟'],
  bounce: ['⣾', '⣽', '⣻', '⢿', '⡿', '⣟', '⣯', '⣷'],
} as const

export type SpinnerType = keyof typeof spinnerFrames

export interface InkUITheme {
  colors: {
    primary: string
    secondary: string
    success: string
    warning: string
    error: string
    info: string
    muted: string
    text: string
    textInverse: string
    border: string
    focus: string
    selection: string
  }
  border: 'single' | 'double' | 'rounded' | 'bold' | 'ascii'
}

export const darkTheme: InkUITheme = {
  colors: {
    primary: 'cyan',
    secondary: 'magenta',
    success: 'green',
    warning: 'yellow',
    error: 'red',
    info: 'blue',
    muted: 'gray',
    text: 'white',
    textInverse: 'black',
    border: 'gray',
    focus: 'cyan',
    selection: 'blue',
  },
  border: 'single',
}

export const lightTheme: InkUITheme = {
  colors: {
    primary: 'blue',
    secondary: 'magenta',
    success: 'green',
    warning: 'yellow',
    error: 'red',
    info: 'cyan',
    muted: 'gray',
    text: 'black',
    textInverse: 'white',
    border: 'gray',
    focus: 'blue',
    selection: 'cyan',
  },
  // Ink Box uses "round", not InkUI's token name "rounded".
  border: 'single',
}

/**
 * craftty default look — same tokens as InkUI dark, slightly warmer focus/primary.
 * Swap this (or pass another theme into ThemeProvider) to recolor the whole TUI.
 */
export const crafttyTheme: InkUITheme = {
  ...darkTheme,
  colors: {
    ...darkTheme.colors,
    primary: '#22d3ee',
    secondary: '#a78bfa',
    success: '#4ade80',
    warning: '#fbbf24',
    error: '#f87171',
    info: '#60a5fa',
    muted: '#9ca3af',
    text: '#f3f4f6',
    textInverse: '#111827',
    border: '#4b5563',
    focus: '#22d3ee',
    selection: '#1e3a5f',
  },
  border: 'single',
}

/** Map InkUI border token → Ink <Box borderStyle>. */
export function toInkBorder(
  style: InkUITheme['border'],
): 'single' | 'double' | 'round' | 'bold' | 'classic' {
  if (style === 'rounded') return 'round'
  if (style === 'ascii') return 'classic'
  return style
}
